### ISSUE TITLE
tendrl-api, wrong release version built

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/tendrl-ci#5]
It seems tendrl-ci is building a wrong version of tendrl-api rpm 

https://copr.fedorainfracloud.org/coprs/tendrl/release/package/tendrl-api/

Current version in copr: 1.3.0

Expected version : 1.5.3

**Comment by dahorak** [comment]
The last build triggered by tendrl-ci job in CentOS CI was https://copr.fedorainfracloud.org/coprs/build/628346/ (with proper version 1.5.3-2 from revision 90bca85c3163a9eb0f912da91227ef8a32eb1df2) as it is visible in the job log: https://ci.centos.org/view/tendrl-build-release/job/tendrl-build-1-release-api/50/console.
So the mentioned builds with version 1.3.0 was triggered by somebody else, not by tendrl-ci jobs in CentOS CI => closing this ticket.

NOTE: we should definitely find the triggering job and disable it to avoid some unexpected mess in the repository. But it is not urgent issue, because the latest versions (1.5.3) are built properly, so it will be used for ordinary installation.
